fixes

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -39,6 +39,10 @@ jobs:
         with:
           java-version: '21'
           distribution: 'temurin'
+      - name: Set up .NET SDK
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: '8.0.x'
       - name: Build with Bazel
         run: bazel build //...
 
@@ -73,6 +77,10 @@ jobs:
         with:
           java-version: '21'
           distribution: 'temurin'
+      - name: Set up .NET SDK
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: '8.0.x'
       - name: Log in to Docker Hub
         uses: docker/login-action@v1
         with:
@@ -84,7 +92,7 @@ jobs:
           GEN_VERSION="v${{ github.run_number }}-$SHORT_SHA"
           
           for target in $(bazel query 'kind(oci_push, //...)'); do
-              bazel run "$target" -- --tag test
+              bazel run "$target" -- --tag $GEN_VERSION
           done
 
   notify-publish:
@@ -258,10 +266,14 @@ jobs:
         run: |
           ORDERS_REPOSITORY="gabrielmirandat/postech-fiap-tc-orders-api"
           MENU_REPOSITORY="gabrielmirandat/postech-fiap-tc-menu-api"
+          PAYMENTS_REPOSITORY="gabrielmirandat/payments"
           SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
           GEN_VERSION="v${{ github.run_number }}-$SHORT_SHA"
           sed -i 's|<ORDERS_API_IMAGE>|'"$ORDERS_REPOSITORY:$GEN_VERSION"'|g' .k8s/orders-api-deployment.yaml
           sed -i 's|<MENU_API_IMAGE>|'"$MENU_REPOSITORY:$GEN_VERSION"'|g' .k8s/menu-api-deployment.yaml
+          if [ -f .k8s/payments-api-deployment.yaml ]; then
+            sed -i 's|<PAYMENTS_API_IMAGE>|'"$PAYMENTS_REPOSITORY:$GEN_VERSION"'|g' .k8s/payments-api-deployment.yaml
+          fi
       - name: Deploy to EKS
         run: |
           kubectl apply -f .k8s/mongodb-secrets.yaml
@@ -277,6 +289,10 @@ jobs:
           kubectl apply -f .k8s/menu-api-service.yaml
           kubectl apply -f .k8s/orders-api-deployment.yaml
           kubectl apply -f .k8s/orders-api-service.yaml
+          if [ -f .k8s/payments-api-deployment.yaml ]; then
+            kubectl apply -f .k8s/payments-api-deployment.yaml
+            kubectl apply -f .k8s/payments-api-service.yaml
+          fi
 
   notify-deploy:
     needs: deploy
@@ -378,6 +394,36 @@ jobs:
           DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: |
           REPOSITORY="gabrielmirandat/postech-fiap-tc-menu-api"
+          TOKEN=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"username\": \"${DOCKER_HUB_USERNAME}\", \"password\": \"${DOCKER_HUB_PASSWORD}\"}" https://hub.docker.com/v2/users/login | jq -r .token)
+          if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
+            echo "Failed to obtain token."
+            exit 1
+          fi
+          TAGS=$(curl -s -H "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/$REPOSITORY/tags" | jq -r '.results | sort_by(.tag_last_pushed) | .[].name')
+          TAGS_ARRAY=($TAGS)
+          TOTAL_TAGS=${#TAGS_ARRAY[@]}
+          KEEP=5
+          DELETE_COUNT=$(($TOTAL_TAGS-$KEEP))
+          if [ $DELETE_COUNT -gt 0 ]; then
+            for ((i=0; i<$DELETE_COUNT; i++)); do
+              TAG=${TAGS_ARRAY[$i]}
+              echo "Deleting tag $TAG from $REPOSITORY..."
+              DELETE_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/$REPOSITORY/tags/$TAG/")
+              if [ "$DELETE_RESPONSE" == "204" ]; then
+                echo "Deleted tag $TAG successfully."
+              else
+                echo "Failed to delete tag $TAG."
+              fi
+            done
+          else
+            echo "No tags to delete. Keeping the latest $KEEP tags."
+          fi
+      - name: List and Delete Old Tags for Payments-API
+        env:
+          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        run: |
+          REPOSITORY="gabrielmirandat/payments"
           TOKEN=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"username\": \"${DOCKER_HUB_USERNAME}\", \"password\": \"${DOCKER_HUB_PASSWORD}\"}" https://hub.docker.com/v2/users/login | jq -r .token)
           if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
             echo "Failed to obtain token."
