start-ruby

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -43,6 +43,11 @@ jobs:
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: '8.0.x'
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: '3.2.0'
+          bundler-cache: true
       - name: Build with Bazel
         run: bazel build //...
 
@@ -81,6 +86,11 @@ jobs:
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: '8.0.x'
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: '3.2.0'
+          bundler-cache: true
       - name: Log in to Docker Hub
         uses: docker/login-action@v1
         with:
@@ -267,12 +277,16 @@ jobs:
           ORDERS_REPOSITORY="gabrielmirandat/postech-fiap-tc-orders-api"
           MENU_REPOSITORY="gabrielmirandat/postech-fiap-tc-menu-api"
           PAYMENTS_REPOSITORY="gabrielmirandat/payments"
+          NOTIFICATIONS_REPOSITORY="gabrielmirandat/notifications"
           SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
           GEN_VERSION="v${{ github.run_number }}-$SHORT_SHA"
           sed -i 's|<ORDERS_API_IMAGE>|'"$ORDERS_REPOSITORY:$GEN_VERSION"'|g' .k8s/orders-api-deployment.yaml
           sed -i 's|<MENU_API_IMAGE>|'"$MENU_REPOSITORY:$GEN_VERSION"'|g' .k8s/menu-api-deployment.yaml
           if [ -f .k8s/payments-api-deployment.yaml ]; then
             sed -i 's|<PAYMENTS_API_IMAGE>|'"$PAYMENTS_REPOSITORY:$GEN_VERSION"'|g' .k8s/payments-api-deployment.yaml
+          fi
+          if [ -f .k8s/notifications-api-deployment.yaml ]; then
+            sed -i 's|<NOTIFICATIONS_API_IMAGE>|'"$NOTIFICATIONS_REPOSITORY:$GEN_VERSION"'|g' .k8s/notifications-api-deployment.yaml
           fi
       - name: Deploy to EKS
         run: |
@@ -292,6 +306,10 @@ jobs:
           if [ -f .k8s/payments-api-deployment.yaml ]; then
             kubectl apply -f .k8s/payments-api-deployment.yaml
             kubectl apply -f .k8s/payments-api-service.yaml
+          fi
+          if [ -f .k8s/notifications-api-deployment.yaml ]; then
+            kubectl apply -f .k8s/notifications-api-deployment.yaml
+            kubectl apply -f .k8s/notifications-api-service.yaml
           fi
 
   notify-deploy:
@@ -424,6 +442,36 @@ jobs:
           DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: |
           REPOSITORY="gabrielmirandat/payments"
+          TOKEN=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"username\": \"${DOCKER_HUB_USERNAME}\", \"password\": \"${DOCKER_HUB_PASSWORD}\"}" https://hub.docker.com/v2/users/login | jq -r .token)
+          if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
+            echo "Failed to obtain token."
+            exit 1
+          fi
+          TAGS=$(curl -s -H "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/$REPOSITORY/tags" | jq -r '.results | sort_by(.tag_last_pushed) | .[].name')
+          TAGS_ARRAY=($TAGS)
+          TOTAL_TAGS=${#TAGS_ARRAY[@]}
+          KEEP=5
+          DELETE_COUNT=$(($TOTAL_TAGS-$KEEP))
+          if [ $DELETE_COUNT -gt 0 ]; then
+            for ((i=0; i<$DELETE_COUNT; i++)); do
+              TAG=${TAGS_ARRAY[$i]}
+              echo "Deleting tag $TAG from $REPOSITORY..."
+              DELETE_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/$REPOSITORY/tags/$TAG/")
+              if [ "$DELETE_RESPONSE" == "204" ]; then
+                echo "Deleted tag $TAG successfully."
+              else
+                echo "Failed to delete tag $TAG."
+              fi
+            done
+          else
+            echo "No tags to delete. Keeping the latest $KEEP tags."
+          fi
+      - name: List and Delete Old Tags for Notifications-API
+        env:
+          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        run: |
+          REPOSITORY="gabrielmirandat/notifications"
           TOKEN=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"username\": \"${DOCKER_HUB_USERNAME}\", \"password\": \"${DOCKER_HUB_PASSWORD}\"}" https://hub.docker.com/v2/users/login | jq -r .token)
           if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
             echo "Failed to obtain token."
